[package]
name = "cpu_6502"
version = "0.1.0"
authors = ["maximveligan <maximveligan@gmail.com>"]
edition = "2024"

[dependencies]
log = "*"
env_logger = "*"
serde = { version = "*", features = ["derive"] }
serde_bytes = "*"
itertools = "*"
bitfield = "*"
